version: "2"

linters:
  enable:
    - gocritic
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - modernize

  settings:
    gocritic:
      enabled-checks:
        - badLock
        - badRegexp
        - badSorting
        - boolExprSimplify
        - builtinShadow
        - builtinShadowDecl
        - commentedOutCode
        - deferInLoop
        - emptyFallthrough
        - equalFold
        - hexLiteral
        - httpNoBody
        - importShadow
        - indexAlloc
        - initClause
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - preferFilepathJoin
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - redundantSprint
        - regexpPattern
        - regexpSimplify
        - returnAfterHttpError
        - sloppyReassign
        - sortSlice
        - sprintfQuotedString
        - sqlQuery
        - stringConcatSimplify
        - stringXbytes
        - timeExprSimplify
        - tooManyResultsChecker
        - truncateCmp
        - typeAssertChain
        - typeDefFirst
        - typeUnparen
        - unlabelStmt
        - unnamedResult
        - unnecessaryBlock
        - unnecessaryDefer
        - weakCond
        - yodaStyleExpr

    nolintlint:
      require-explanation: true
      require-specific: true

  exclusions:
    presets:
      - common-false-positives
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
