// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReviewComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddReviewComment'](arg1, arg2, arg3);
}

export function ApprovePlan(arg1) {
  return window['go']['main']['App']['ApprovePlan'](arg1);
}

export function AttachAgent(arg1) {
  return window['go']['main']['App']['AttachAgent'](arg1);
}

export function AttachOrchestrator() {
  return window['go']['main']['App']['AttachOrchestrator']();
}

export function AttachTmuxSession(arg1) {
  return window['go']['main']['App']['AttachTmuxSession'](arg1);
}

export function CaptureAgentPane(arg1) {
  return window['go']['main']['App']['CaptureAgentPane'](arg1);
}

export function CaptureOrchestratorPane() {
  return window['go']['main']['App']['CaptureOrchestratorPane']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteReviewComment(arg1, arg2) {
  return window['go']['main']['App']['DeleteReviewComment'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DiscoverAgents() {
  return window['go']['main']['App']['DiscoverAgents']();
}

export function EvaluateTask(arg1, arg2) {
  return window['go']['main']['App']['EvaluateTask'](arg1, arg2);
}

export function FetchReviews() {
  return window['go']['main']['App']['FetchReviews']();
}

export function GetAgentOutput(arg1) {
  return window['go']['main']['App']['GetAgentOutput'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function IsOrchestratorRunning() {
  return window['go']['main']['App']['IsOrchestratorRunning']();
}

export function KillTmuxSession(arg1) {
  return window['go']['main']['App']['KillTmuxSession'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListNotifications() {
  return window['go']['main']['App']['ListNotifications']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListReviewComments(arg1) {
  return window['go']['main']['App']['ListReviewComments'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListTmuxSessions() {
  return window['go']['main']['App']['ListTmuxSessions']();
}

export function ListWorktrees(arg1) {
  return window['go']['main']['App']['ListWorktrees'](arg1);
}

export function MarkPRReady(arg1, arg2) {
  return window['go']['main']['App']['MarkPRReady'](arg1, arg2);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function PlanTask(arg1) {
  return window['go']['main']['App']['PlanTask'](arg1);
}

export function RegisterSpotlightHotkey() {
  return window['go']['main']['App']['RegisterSpotlightHotkey']();
}

export function RejectPlan(arg1, arg2) {
  return window['go']['main']['App']['RejectPlan'](arg1, arg2);
}

export function ResolveReviewComment(arg1, arg2) {
  return window['go']['main']['App']['ResolveReviewComment'](arg1, arg2);
}

export function SetDesktopNotifications(arg1) {
  return window['go']['main']['App']['SetDesktopNotifications'](arg1);
}

export function StartAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAgent'](arg1, arg2, arg3);
}

export function StartOrchestrator() {
  return window['go']['main']['App']['StartOrchestrator']();
}

export function StartReview(arg1) {
  return window['go']['main']['App']['StartReview'](arg1);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function StopOrchestrator() {
  return window['go']['main']['App']['StopOrchestrator']();
}

export function TriageTask(arg1) {
  return window['go']['main']['App']['TriageTask'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
