// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachAgent(arg1) {
  return window['go']['main']['App']['AttachAgent'](arg1);
}

export function AttachOrchestrator() {
  return window['go']['main']['App']['AttachOrchestrator']();
}

export function AttachTmuxSession(arg1) {
  return window['go']['main']['App']['AttachTmuxSession'](arg1);
}

export function CaptureAgentPane(arg1) {
  return window['go']['main']['App']['CaptureAgentPane'](arg1);
}

export function CaptureOrchestratorPane() {
  return window['go']['main']['App']['CaptureOrchestratorPane']();
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DiscoverAgents() {
  return window['go']['main']['App']['DiscoverAgents']();
}

export function GetAgentOutput(arg1) {
  return window['go']['main']['App']['GetAgentOutput'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function IsOrchestratorRunning() {
  return window['go']['main']['App']['IsOrchestratorRunning']();
}

export function KillTmuxSession(arg1) {
  return window['go']['main']['App']['KillTmuxSession'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListTmuxSessions() {
  return window['go']['main']['App']['ListTmuxSessions']();
}

export function StartAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAgent'](arg1, arg2, arg3);
}

export function StartOrchestrator() {
  return window['go']['main']['App']['StartOrchestrator']();
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function StopOrchestrator() {
  return window['go']['main']['App']['StopOrchestrator']();
}

export function TriageTask(arg1) {
  return window['go']['main']['App']['TriageTask'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
