// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {agent} from '../models';
import {github} from '../models';
import {tmux} from '../models';

export function AttachAgent(arg1:string):Promise<void>;

export function AttachOrchestrator():Promise<void>;

export function AttachTmuxSession(arg1:string):Promise<void>;

export function CaptureAgentPane(arg1:string):Promise<string>;

export function CaptureOrchestratorPane():Promise<string>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<task.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function DiscoverAgents():Promise<Array<agent.Agent>>;

export function EvaluateTask(arg1:string,arg2:string):Promise<void>;

export function FetchReviews():Promise<github.ReviewSummary>;

export function GetAgentOutput(arg1:string):Promise<Array<agent.StreamEvent>>;

export function GetTask(arg1:string):Promise<task.Task>;

export function IsOrchestratorRunning():Promise<boolean>;

export function KillTmuxSession(arg1:string):Promise<void>;

export function ListAgents():Promise<Array<agent.Agent>>;

export function ListTasks():Promise<Array<task.Task>>;

export function ListTmuxSessions():Promise<Array<tmux.SessionInfo>>;

export function RegisterSpotlightHotkey():Promise<void>;

export function StartAgent(arg1:string,arg2:string,arg3:string):Promise<agent.Agent>;

export function StartOrchestrator():Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function StopOrchestrator():Promise<void>;

export function TriageTask(arg1:string):Promise<void>;

export function UpdateTask(arg1:string,arg2:Record<string, any>):Promise<task.Task>;
